kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: guestbook-app
  name: redis-master-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
